version: '3.6'
# indentations matter in 'yml' files
services:
  smart-brain-api:
    container_name: backend
    # image: node:8.16.2
    build: ./
    # builds from source using Dockerfile
    command: npm start
    working_dir: /usr/src/smart-brain-api
    # proper directory (package.json)
    ports:
      - "3000:3000"
    # maps containers internal port to the host
    volumes:
      - ./:/usr/src/smart-brain-api
    # 'volumes' allows access into the file system to update Docker container based on local changes